 # Get base SDK image from microsoft
FROM mcr.microsoft.com/dotnet/core/sdk AS build-env
WORKDIR /app

# Copy project file and restore project dependencies
COPY *.csproj ./
RUN dotnet restore 

# Copy the project file and build our release
COPY . ./
RUN dotnet publish -c Release -o out

# Generate runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet
WORKDIR /app
EXPOSE 80
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet","RecipositoryApi.dll"]